os:
  - linux
language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-multilib
script:
  - make -C Test clean
  - make -C Test x86linux32
  - make -C Test clean
  - make -C Test x86linux64
---
os:
  - windowsxp
language: c
compiler:
  - gcc
  - clang
script:
  - make -C Test clean
  - make -C Test x86win32
  - make -C Test clean
  - make -C Test x86win64